apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: csaa-app-only
  
metadata:
  name: csaa-app-only
  annotations:
    openshift.io/display-name: css application template
    description: The RMM agent application
    iconClass: icon-java
    tags: java
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: ${APP_NAME}
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: ${REPLICAS}
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: APP_MSG
            value: ${APP_MSG} 
          image: quay.io/hsaid4326/myapp:${IMAGE_TAG}
          imagePullPolicy: Always
          name: ${APP_NAME}
          resources: {}
          readinessProbe:
            httpGet:
              path: /hello/api/hello
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3            
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []


parameters:
- name: NAMESPACE
  displayName: namespace of the project for application
  description: The namespace of the project for application
  required: true
- name: APP_MSG
  displayName: Database Password
  description: Password to access the database
- name: IMAGE_TAG
  displayName: IMAGE TAG
  description: Image tag
  required: true
  value: stable
- name: APP_NAME
  displayName: APP NAME
  description: Name of the application to be deployed
  required: true
- name: REPLICAS
  displayName: Application Instances
  description: Application instances
  required: true
