pipeline {
    
    agent {
        label 'csaa-agent'
     }
  parameters {
        string(name: 'APP_MSG', defaultValue: 'Default Message from application', description: 'Message to pass to deployment?')
  
        choice(name: 'Environment', choices: ['csaa-dev', 'csaa-qa'], description: 'Pick environment to deploy your application')
  }    

    stages{
    
      stage("Deploy Application Image"){
           steps{
              container("jnlp"){
                 script{
                   openshift.withCluster() {
                     openshift.withProject("csaa-dev") {
                         def rm = openshift.selector("dc", "myapp").rollout().latest()
                         
                         timeout(5) { 
                             openshift.selector("dc", "myapp").related('pods').untilEach(1) {
                             return (it.object().status.phase == "Running")
                            }
                    
                         } //end of timeout

                       }//withProject
                   } //withcluster   
                 }//script

              }//container
                
            }
        } 
    }

 }//end of pipeline

