pipeline {
    
    agent {
        label 'csaa-agent'
     }
  parameters {
        string(name: 'APP_MSG', defaultValue: 'Default Message from application', description: 'Message to pass to deployment?')
  
        choice(name: 'Environment', choices: ['csaa-dev', 'csaa-qa'], description: 'Pick environment to deploy your application')
  }    

    stages{
    
      stage("Deploy Application Image"){
            steps{
              container("jnlp"){
                echo "This is the first stage"

                }
                
            }
        } //end of stage

 }//end of pipeline
    
  
}
