def DEV_PROJ = 'csaa-dev'
def STAGE_DIR = '/opt/app/myapp/'

def prebuild () {
        sh 'mkdir -p ' + STAGE_DIR + 'deployments'        
    }


pipeline {
    
    agent {
        label 'csaa-agent'
    }
    

    stages{
        stage("Application Artifact Build"){
            steps{
              container("jnlp"){
                 script {
                 prebuild ()
                 
                  sh '''cd app-src
                  mvn clean package -DskipTests=true''' 
                }
                  
              }
                
            }
        }

   stage("Copy Artifact to stage"){
            steps{
              container("jnlp"){
                 
                  sh 'cp app-src/stage/hello.war ' + STAGE_DIR + 'deployments'        
                  
                  
              }
                
            }
        }
        
        stage("skope stage"){
            steps{
                container("skopeo"){
                    sh "skopeo --version"
                }
                
            }
        }
    }
}
