DEV_PROJ = 'csaa-dev'
STAGE_DIR = '/tmp/workspace/myapp/'

def prebuild () {
        sh 'mkdir -p ' + STAGE_DIR + 'deployments'        
    }


pipeline {
    
    agent {
        label 'csaa-agent'
    }
    

    stages{
        stage("Application Artifact Build"){
            steps{
              container("jnlp"){
                 script {
                 prebuild ()
                 
                  sh '''cd app-src
                  mvn clean package -DskipTests=true''' 
                }
                  
              }
                
            }
        }

   stage("Copy Artifact to stage"){
            steps{
              container("jnlp"){
                 
                  sh 'cp app-src/target/hello.war ' + STAGE_DIR + 'deployments'        
                  
                  
              }
                
            }
        }
        
      stage("Build Application Image"){
            steps{
              container("jnlp"){
                 
          script {
              openshift.withCluster() {
                openshift.withProject("${DEV_PROJ}") {
                  openshift.selector("bc", "myapp").startBuild("--from-dir=/tmp/workspace/myapp", "--wait=true")
                  
        
                  }
               }
            } 
        
              }
                
            }
        }
                
    
    stage("Push Image to external repo"){
      input 'Ready to push image to external registry?'       
            
            steps{
                container("skopeo"){
                    sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds hsaid4327:NabIla4327 docker://image-registry.openshift-image-registry.svc.cluster.local:5000/${DEV_PROJ}/myapp:latest docker://quay.io/hsaid4327/csaa/myapp:stable"
                }
                
            }
        }
    }
}
