pipeline {
    
    agent {
        label 'csaa-agent'
    }
    options { timestamps () }
    
    stages{
        stage("Application Artifact Build"){
            steps{
              container("jnlp"){
                 
                  sh 'cd app-src;mvn clean install'
                  
              }
                
            }
        }
        stage("skope stage"){
            steps{
                container("skopeo"){
                    sh "skopeo --version"
                }
                
            }
        }
    }
}
